[package]
name = "aoc_2020"
version = "0.1.0"
authors = ["Samedh Gupta <samedh.gupta@pathai.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.34"
